---
- hosts: all
  become: yes
  tasks:
    - name: Install gopls
      snap: 
        name: gopls
        classic: yes
    - name: Pull neovim
      git:
        repo: https://github.com/neovim/neovim.git
        dest: /home/repos/neovim
        clone: yes
        update: yes
    - name: Install neovim
      shell: |
        cd /home/repos/neovim 
        git checkout stable
        make
        sudo make install



