---
- hosts: all
  tasks:
    - name: Install gopls
      snap: 
        name: gopls
        classic: yes

    - name: Install node
      apt:
        name: nodejs

    - name: Install LSP
      npm: 
        name: vim-language-server
        global: yes

    - name: Pull neovim
      git:
        repo: https://github.com/neovim/neovim.git
        dest: /home/repos/neovim
        clone: yes
        update: yes
        force: yes

    - name: Install neovim
      shell: |
        cd /home/repos/neovim 
        git checkout stable
        make
        sudo make install
        git checkout master

    - name: Install maim
      apt:
        name: maim

    - name: Install i3
      apt:
        name: i3

    - name: Add speed ricer repo
      apt_repository: 
        repo: ppa:kgilmer/speed-ricer
        state: present
    
    - name: Install speed ricer
      apt:
        name: i3-gaps

    - name: Install tmux
      apt:
        name: tmux
